### ISSUE TITLE
No 64Bit support?

### ISSUE THREAD

**Issue by aKalisch** [ReactiioN1337/valve-bsp-parser#2]
Does this not support x86_x64 ?

<img width="865" alt="bildschirmfoto 2016-10-04 um 12 30 44" src="https://cloud.githubusercontent.com/assets/3403599/19071043/6a98e224-8a2e-11e6-8037-3a567b7e97d7.png">

@ReactiioN1337

**Comment by w3bn00b** [comment]
build it on release x86

**Comment by ReactiioN1337** [comment]
Hi @aKalisch, the current `develop` branch works flawless for both architectures. The main namespace has been renamed to `mkrn`, otherwise you don't have to modify anything else for the time being.
