### ISSUE TITLE
Is it viable to list map entities?

### ISSUE THREAD

**Issue by Henroks** [ReactiioN1337/valve-bsp-parser#4]
Hello. 
Im trying to list all entities on the map (player_spawn, teleport_target, light sources, etc).

Id love to contribute with this repo, is there a starting point or any kind of guidance to what should I do to archive that?

**Comment by MrSoup678** [comment]
This parser does not support entity parsing. My fork plans to support that.

But basically all entities are present in lump  0 of BSP file. This file may live in sefarate file (.lmp). This behavior is not yet supported in my fork.

 Some games also support lump compressing via LZMA. My fork already supports that.

**Comment by ReactiioN1337** [comment]
Will be possible after merging #3

**Comment by ReactiioN1337** [comment]
Thanks to @SlawekNowy for his contribution, you can use for now the `develop` branch until 2.0.0 is finished.
