### ISSUE TITLE
Linker error

### ISSUE THREAD

**Issue by 20scrolls** [ReactiioN1337/valve-bsp-parser#6]
I have this error that I cannot seem to get rid of, I don't know if its my visual studios fault or the code itself.

"unresolved external symbol WinMain referenced in function "int __cdecl invoke_main(void)" (?invoke_main@@YAHXZ)"

**Comment by ReactiioN1337** [comment]
Configure the project as `Static Library` instead of `Application`.  Will fix this in the near future and setup a proper CI/CD, so you can optional use the precompiled binaries.

**Comment by ReactiioN1337** [comment]
#8 solved this issue
